demo_config_entity.info:
  path: '/demo/configuration-entity'
  defaults:
    _controller: '\Drupal\demo_config_entity\Controller\DemoConfigEntityController::infoPage'
    _title: 'Configuration Entities'
  requirements:
    _permission: 'access content'

demo_config_entity.add:
  path: '/demo/configuration-entity/add'
  defaults:
    _form: '\Drupal\demo_config_entity\Form\AddWebserviceForm'
    _title: 'Configuration Entity'
  requirements:
    _permission: 'access content'

